# Generated by Django 5.2.10 on 2026-02-10 12:49

import django.db.models.deletion
import messenger.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='last_media_upload',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последняя загрузка медиа'),
        ),
        migrations.AddField(
            model_name='chatroom',
            name='total_media_files',
            field=models.IntegerField(default=0, verbose_name='Всего медиафайлов'),
        ),
        migrations.AddField(
            model_name='message',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время редактирования'),
        ),
        migrations.AddField(
            model_name='message',
            name='is_edited',
            field=models.BooleanField(default=False, verbose_name='Редактировано'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Текстовое'), ('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио'), ('document', 'Документ'), ('voice', 'Голосовое')], default='text', max_length=10, verbose_name='Тип сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, verbose_name='Текст сообщения'),
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=messenger.models.media_upload_path, verbose_name='Файл')),
                ('file_type', models.CharField(choices=[('image', 'Изображение'), ('video', 'Видео'), ('audio', 'Аудио'), ('document', 'Документ'), ('voice', 'Голосовое сообщение')], max_length=10, verbose_name='Тип файла')),
                ('file_name', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('file_size', models.BigIntegerField(verbose_name='Размер файла (байты)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIME-тип')),
                ('duration', models.IntegerField(default=0, help_text='Длительность аудио/видео в секундах', verbose_name='Длительность')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=messenger.models.thumbnail_upload_path, verbose_name='Миниатюра')),
                ('caption', models.TextField(blank=True, verbose_name='Описание')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Время загрузки')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Удален')),
                ('views_count', models.IntegerField(default=0, verbose_name='Количество просмотров')),
                ('downloads_count', models.IntegerField(default=0, verbose_name='Количество скачиваний')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='messenger.chatroom')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Медиафайл',
                'verbose_name_plural': 'Медиафайлы',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='media_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messenger.mediafile'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['chat', 'timestamp'], name='messenger_m_chat_id_8a762c_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'timestamp'], name='messenger_m_sender__3ecdaf_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', 'timestamp'], name='messenger_m_message_1ce927_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['chat', 'uploaded_at'], name='messenger_m_chat_id_82a21b_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['file_type', 'uploaded_at'], name='messenger_m_file_ty_09846c_idx'),
        ),
        migrations.AddIndex(
            model_name='mediafile',
            index=models.Index(fields=['sender', 'uploaded_at'], name='messenger_m_sender__4e00e6_idx'),
        ),
    ]
